### ISSUE TITLE
Linux Mint 17.2 Rafaela

### ISSUE THREAD

**Issue by Splarv** [shuairan/gTile#38]
Don't work in Linux Mint 17.2 Rafaela, Cinnamon version 2.6.11+rafaela. Log said that the this version is not supported.

**Comment by nikhilgk** [comment]
Submitted Pull request #39 to fix this. As a temporary work around, Right Click Panel > Troubleshoot... > Looking Glass > Extensions > Right click Extensions | gTile > gTile@shuarian (View Source).
Edit the file metadata.json and add version 2.6 so that the line 2 looks like:    

`"cinnamon-version": ["1.8", "2.0", "2.2", "2.4", "2.6"], `

Save and exit and restart cinnamon either by pressing Alt F2 and typing 'r' and enter or by logging out and logging back in.
